definitions:
  services:
    docker:
      memory: 4096

pipelines:
  branches:
    master:
      - step:
          name: pub
          size: 2x
          services:
            - docker
          caches:
            - docker
          script:
            - export IMAGE_NAME=$DOCKER_REGISTRY_DOMAIN/$DOCKER_REGISTRY_USERNAME/pub:$BITBUCKET_BRANCH
            - docker build -t $IMAGE_NAME .
            - docker login --username $DOCKER_REGISTRY_USERNAME --password $DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY_DOMAIN
            - docker push $IMAGE_NAME
    release:
      - step:
          name: pub
          size: 2x
          services:
            - docker
          script:
            - echo -e 'Host 192.168.0.*\n\tUser huoju\n\tForwardAgent yes\n\tProxyCommand ssh huoju@139.198.2.168 nc %h %p' >> ~/.ssh/config && ssh -o StrictHostKeyChecking=no huoju@192.168.0.3 "sudo chmod 755 -R build_shortcuts && cd ./build_shortcuts && ./14_build_pub.sh"
